export const Users = [
    {
      id:1,
      profilePicture: "assets/profiles/fatima.jpeg",
      username: "Fatima",
    },
    {
      id:2,
      profilePicture: "profiles/abdullah.jpeg",
      username: "Abdullah Sohail",
    },
    {
      id:3,
      profilePicture: "profiles/aliha.jpeg",
      username: "Seemal Arif",
    },
    {
      id:4,
      profilePicture: "profiles/sarah.jpeg",
      username: "Sarah Rafi",
    },
    {
      id:5,
      profilePicture: "profiles/faiza.jpeg",
      username: "Faiza Azam",
    },
    {
      id:6,
      profilePicture: "profiles/osama.jpeg",
      username: "Osama Zahid",
    },
    {
      id:7,
      profilePicture: "profiles/hassan.jpeg",
      username: "Hassan Shahzad",
    },
    {
      id:8,
      profilePicture: "profiles/mohsin.jpeg",
      username: "Mohsin Khalid",
    },
    {
      id:9,
      profilePicture: "profiles/mahnoor.jpeg",
      username: "Mahnoor Amjad",
    },
    {
      id:10,
      profilePicture: "assets/profiles/amina.jpeg",
      username: "Amina Awais",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Hiring Alert!!",
      photo: "posts/hire1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "posts/hire2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "posts/hire3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "posts/hire4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "posts/hire5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "posts/hire6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Associate Software engineers Alert!!.",
      photo: "posts/hire7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "posts/hire8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself. Opening our hiring process",
      photo: "assets/posts/hire9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "posts/hire10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
